name: Auto Regenerate CHANGELOG.md
on:
  workflow_run:
    workflows: [test]
    types: [completed]
    branches: [main]

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@v1.2.0
        with:
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH: 'CHANGELOG.md'
          TYPE: 'none:none'
