name: Regenerate CHANGELOG.md
on:
  workflow_dispatch:
    inputs:
      target:
        description: 'choose number of changes note to regen'
        default: '-1'
        required: true

jobs:
  generate-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: BobAnkh/auto-generate-changelog@v1.2.0
        with:
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          PATH: 'CHANGELOG.md'
          REGENERATE_COUNT: "${{ github.event.inputs.target }}"
          TYPE: 'none:none'
          BRANCH: 'documentation'
          PULL_REQUEST: 'main'



